### ISSUE TITLE
Clean up email/username confusion

### ISSUE THREAD

**Issue by perryahern** [LambdaSchool/Client-Auth#31]
There's a disconnect in this project concerning the use of either a username or email address for the signup, login, etc. Consensus is that it should be username throughout, and the TAs confirmed that there was confusion for their class as well when they saw this. It should be made consistent throughout for the benefit of future classes.

**Comment by seanchen1991** [comment]
I went through and changed all variable names from `email` to `username`. Hopefully that clears up any confusion.
